import argparse
from pathlib import Path

import pandas as pd

from backtest.simulator import BacktestSimulator
from data.market_data import MarketDataService
from data.universe import (
    DEFAULT_UNIVERSE,
    load_sp500_symbols,
    load_symbols_file,
    parse_symbols,
)
from strategies.score_engine import score_stock
from portfolio.portfolio import Portfolio
from strategies.signal_engine import generate_signals
from indicators.market import market_regime_score


def run_simulation(symbols):
    market = MarketDataService()
    benchmark = market.get_history("SPY")
    market_regime = market_regime_score(benchmark)

    portfolio = Portfolio(
        starting_cash=100000
    )

    results = []

    for symbol in symbols:

        df = market.get_history(symbol)

        if df.empty:
            continue

        metrics = score_stock(symbol, df, market_regime)

        results.append(metrics)

    signals = generate_signals(results)

    portfolio.rebalance(signals)

    portfolio.print_summary()


DEFAULT_LOOKBACK_DAYS = 253
DEFAULT_TRADES_CSV = "transactions.csv"
DEFAULT_STOP_LOSS_PCT = 0.05
DEFAULT_TRAILING_STOP_PCT = 0.15


def run_backtest(
    symbols,
    buy_check_days=5,
    sell_check_days=1,
    trades_limit=None,
    start_date=None,
    end_date=None,
    trades_csv=None,
    stop_loss_pct=DEFAULT_STOP_LOSS_PCT,
    trailing_stop_pct=DEFAULT_TRAILING_STOP_PCT,
):
    market = MarketDataService()
    history = {}
    download_start = calculate_download_start(start_date, DEFAULT_LOOKBACK_DAYS)
    download_end = calculate_download_end(end_date)

    for symbol in symbols:
        df = market.get_history(symbol, start=download_start, end=download_end)

        if not df.empty:
            history[symbol] = df

    benchmark = market.get_history("SPY", start=download_start, end=download_end)

    simulator = BacktestSimulator(
        price_history=history,
        benchmark_history=benchmark,
        starting_cash=100000,
        lookback_days=DEFAULT_LOOKBACK_DAYS,
        buy_check_days=buy_check_days,
        sell_check_days=sell_check_days,
        start_date=start_date,
        end_date=end_date,
        stop_loss_pct=stop_loss_pct,
        trailing_stop_pct=trailing_stop_pct,
    )
    result = simulator.run()

    print("\nBacktest\n")
    print(f"Starting cash: ${result['starting_cash']:.2f}")
    print(f"Ending value:  ${result['ending_value']:.2f}")
    print(f"Total return:  {result['total_return']:.2%}")
    print(f"Start date:    {start_date or 'Downloaded history start'}")
    print(f"End date:      {end_date or 'Downloaded history end'}")
    print(f"Buy checks:    Every {buy_check_days} trading day(s)")
    print(f"Sell checks:   Every {sell_check_days} trading day(s)")
    print(f"Hard stop:     {stop_loss_pct:.2%}")
    print(f"Trailing stop: {trailing_stop_pct:.2%}")
    print(f"Trades:        {len(result['trades'])}")
    print_transaction_history(result["trades"], trades_limit)

    if trades_csv:
        csv_path = export_transaction_history(result["trades"], trades_csv)
        print(f"\nTransaction CSV written to {csv_path}")


def format_trade_date(value):
    if hasattr(value, "strftime"):
        return value.strftime("%Y-%m-%d")

    return str(value)


def format_optional_money(value):
    if value is None:
        return "-"

    return f"${value:,.2f}"


def format_optional_pct(value):
    if value is None:
        return "-"

    return f"{value:.2%}"


def print_transaction_history(trades, limit=None):
    print("\nTransaction History\n")

    if not trades:
        print("No transactions were generated by this backtest.")
        return

    visible_trades = trades if limit is None else trades[:limit]
    header = (
        f"{'Date':10} "
        f"{'Side':4} "
        f"{'Symbol':6} "
        f"{'Shares':>10} "
        f"{'Price':>11} "
        f"{'Value':>13} "
        f"{'Rating':>7} "
        f"{'Reason':14} "
        f"{'P/L':>12} "
        f"{'P/L %':>8} "
        f"{'Days':>6}"
    )
    print(header)
    print("-" * len(header))

    for trade in visible_trades:
        holding_days = trade["holding_days"]
        holding_days = "-" if holding_days is None else str(holding_days)

        print(
            f"{format_trade_date(trade['date']):10} "
            f"{trade['side']:4} "
            f"{trade['symbol']:6} "
            f"{trade['shares']:10.2f} "
            f"${trade['price']:10.2f} "
            f"${trade['value']:12,.2f} "
            f"{trade['rating']:7.2f} "
            f"{trade.get('reason', '-'):14} "
            f"{format_optional_money(trade['pnl']):>12} "
            f"{format_optional_pct(trade['pnl_pct']):>8} "
            f"{holding_days:>6}"
        )

    if limit is not None and len(trades) > limit:
        remaining = len(trades) - limit
        print(f"\n... {remaining} more transaction(s) not shown.")


def export_transaction_history(trades, path):
    columns = [
        "date",
        "side",
        "symbol",
        "shares",
        "price",
        "value",
        "rating",
        "reason",
        "entry_date",
        "entry_price",
        "cost_basis",
        "pnl",
        "pnl_pct",
        "holding_days",
    ]
    rows = []

    for trade in trades:
        row = {}

        for column in columns:
            row[column] = trade.get(column)

        row["date"] = format_trade_date(row["date"])

        if row["entry_date"] is not None:
            row["entry_date"] = format_trade_date(row["entry_date"])

        rows.append(row)

    csv_path = Path(path)

    if csv_path.parent != Path("."):
        csv_path.parent.mkdir(parents=True, exist_ok=True)

    pd.DataFrame(rows, columns=columns).to_csv(csv_path, index=False)
    return csv_path


def resolve_symbols(args):
    if args.symbols:
        symbols = parse_symbols(args.symbols)
    elif args.symbols_file:
        symbols = load_symbols_file(args.symbols_file)
    elif args.universe == "sp500":
        try:
            symbols = load_sp500_symbols()
        except Exception as error:
            print(f"Could not load S&P 500 universe: {error}")
            print("Falling back to built-in default universe.")
            symbols = DEFAULT_UNIVERSE
    else:
        symbols = DEFAULT_UNIVERSE

    if args.limit:
        symbols = symbols[:args.limit]

    return symbols


def positive_int(value):
    parsed = int(value)

    if parsed < 1:
        raise argparse.ArgumentTypeError("must be at least 1")

    return parsed


def pct_float(value):
    parsed = float(value)

    if parsed < 0 or parsed >= 1:
        raise argparse.ArgumentTypeError("must be between 0 and 1")

    return parsed


def valid_date(value):
    try:
        return pd.Timestamp(value).strftime("%Y-%m-%d")
    except ValueError as error:
        raise argparse.ArgumentTypeError("must be YYYY-MM-DD") from error


def calculate_download_start(start_date, lookback_days):
    if not start_date:
        return None

    warmup_days = lookback_days * 2
    return (pd.Timestamp(start_date) - pd.Timedelta(days=warmup_days)).strftime(
        "%Y-%m-%d"  
    )


def calculate_download_end(end_date):
    if not end_date:
        return None

    return (pd.Timestamp(end_date) + pd.Timedelta(days=1)).strftime("%Y-%m-%d")


def validate_date_range(start_date, end_date):
    if start_date and end_date and pd.Timestamp(end_date) < pd.Timestamp(start_date):
        raise SystemExit("--end-date must be on or after --start-date")


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--backtest",
        action="store_true",
        help="Run a historical rolling-window backtest instead of today's signals.",
    )
    parser.add_argument(
        "--symbols",
        help="Comma-separated symbols to scan instead of the default universe.",
    )
    parser.add_argument(
        "--symbols-file",
        help="Path to a symbol file. Supports comma, space, or newline-separated symbols.",
    )
    parser.add_argument(
        "--universe",
        choices=["default", "sp500"],
        default="sp500",
        help="Stock universe to scan when --symbols or --symbols-file is not provided.",
    )
    parser.add_argument(
        "--limit",
        type=int,
        help="Only use the first N symbols from the selected universe.",
    )
    parser.add_argument(
        "--trades-limit",
        type=int,
        help="Only print the first N transactions from a backtest.",
    )
    parser.add_argument(
        "--trades-csv",
        default=DEFAULT_TRADES_CSV,
        help="Write the full backtest transaction history to this CSV path.",
    )
    parser.add_argument(
        "--no-trades-csv",
        action="store_true",
        help="Do not write a backtest transaction CSV.",
    )
    parser.add_argument(
        "--buy-check-days",
        type=positive_int,
        default=5,
        help="How often the backtest checks for new buys, in trading days.",
    )
    parser.add_argument(
        "--sell-check-days",
        type=positive_int,
        default=1,
        help="How often the backtest checks existing positions for sells, in trading days.",
    )
    parser.add_argument(
        "--stop-loss-pct",
        type=pct_float,
        default=DEFAULT_STOP_LOSS_PCT,
        help="Hard stop loss from entry price, as a decimal. Use 0 to disable.",
    )
    parser.add_argument(
        "--trailing-stop-pct",
        type=pct_float,
        default=DEFAULT_TRAILING_STOP_PCT,
        help="Trailing stop from highest close since entry, as a decimal. Use 0 to disable.",
    )
    parser.add_argument(
        "--start-date",
        type=valid_date,
        help="Backtest start date, formatted YYYY-MM-DD.",
    )
    parser.add_argument(
        "--end-date",
        type=valid_date,
        help="Backtest end date, formatted YYYY-MM-DD.",
    )
    args = parser.parse_args()
    validate_date_range(args.start_date, args.end_date)
    symbols = resolve_symbols(args)

    print(f"Scanning {len(symbols)} symbols.")

    if args.backtest:
        run_backtest(
            symbols,
            buy_check_days=args.buy_check_days,
            sell_check_days=args.sell_check_days,
            trades_limit=args.trades_limit,
            start_date=args.start_date,
            end_date=args.end_date,
            trades_csv=None if args.no_trades_csv else args.trades_csv,
            stop_loss_pct=args.stop_loss_pct,
            trailing_stop_pct=args.trailing_stop_pct,
        )
    else:
        run_simulation(symbols)
